Switched to branch 'daily'
Traceback (most recent call last):
  File "./01.interactive.e2e.py", line 46, in <module>
    root_run = Run.start_logging(workspace = ws, run_history_name = run_history_name)
TypeError: start_logging() missing 1 required positional argument: 'history_name'
Traceback (most recent call last):
  File "./02.local.py", line 30, in <module>
    directory = project_folder)
TypeError: attach() got an unexpected keyword argument 'run_history_name'
Traceback (most recent call last):
  File "./03.aci.py", line 31, in <module>
    directory = project_folder)
TypeError: attach() got an unexpected keyword argument 'run_history_name'
Traceback (most recent call last):
  File "./04.dsvm.py", line 30, in <module>
    directory = project_folder)
TypeError: attach() got an unexpected keyword argument 'run_history_name'
Traceback (most recent call last):
  File "./05.spark.py", line 30, in <module>
    directory = project_folder)
TypeError: attach() got an unexpected keyword argument 'run_history_name'
Traceback (most recent call last):
  File "./07.sklearn.hd.py", line 32, in <module>
    directory = project_folder)
TypeError: attach() got an unexpected keyword argument 'run_history_name'
Traceback (most recent call last):
  File "./08.tf.hd.py", line 33, in <module>
    directory = project_folder)
TypeError: attach() got an unexpected keyword argument 'run_history_name'
Client-Request-ID=a81d7564-68ea-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Tue, 05 Jun 2018 18:02:48 GMT, Server-Request-ID=9a210233-701e-0076-2ff7-fcafe1000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:9a210233-701e-0076-2ff7-fcafe1000000Time:2018-06-05T18:02:48.8018268Z</Message></Error>.
Client-Request-ID=a81d7566-68ea-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Tue, 05 Jun 2018 18:02:48 GMT, Server-Request-ID=b30effb3-101e-005f-67f7-fc9195000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:b30effb3-101e-005f-67f7-fc9195000000Time:2018-06-05T18:02:48.9600981Z</Message></Error>.
Client-Request-ID=a81d7568-68ea-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Tue, 05 Jun 2018 18:02:49 GMT, Server-Request-ID=9c646fd3-701e-0066-12f7-fc6a89000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:9c646fd3-701e-0066-12f7-fc6a89000000Time:2018-06-05T18:02:49.1203217Z</Message></Error>.
Client-Request-ID=a81d756a-68ea-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Tue, 05 Jun 2018 18:02:48 GMT, Server-Request-ID=c1b2825b-401e-0052-05f7-fc5941000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:c1b2825b-401e-0052-05f7-fc5941000000Time:2018-06-05T18:02:49.2788192Z</Message></Error>.
Traceback (most recent call last):
  File "./10.o16n.py", line 80, in <module>
    for w in ws.list_webservices():
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/site-packages/azureml/core/workspace.py", line 876, in list_webservices
    return Webservice.list(self)
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/site-packages/azureml/core/webservice/webservice.py", line 379, in list
    service_obj = child.deserialize(workspace, service_dict)
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/site-packages/azureml/core/webservice/aci.py", line 272, in deserialize
    webservice = AciWebservice(None)
TypeError: __init__() missing 1 required positional argument: 'name'
Switched to branch 'master'
