error: pathspec 'daily' did not match any file(s) known to git.
Client-Request-ID=94630f51-67de-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Mon, 04 Jun 2018 10:03:50 GMT, Server-Request-ID=97a54ea6-901e-007e-32eb-fbb5ee000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:97a54ea6-901e-007e-32eb-fbb5ee000000Time:2018-06-04T10:03:51.1444825Z</Message></Error>.
Client-Request-ID=94630f53-67de-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Mon, 04 Jun 2018 10:03:51 GMT, Server-Request-ID=bcb0af81-d01e-0040-33eb-fb2291000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:bcb0af81-d01e-0040-33eb-fb2291000000Time:2018-06-04T10:03:51.3003857Z</Message></Error>.
Client-Request-ID=94630f55-67de-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Mon, 04 Jun 2018 10:03:50 GMT, Server-Request-ID=e5d8c456-901e-006e-51eb-fb7086000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:e5d8c456-901e-006e-51eb-fb7086000000Time:2018-06-04T10:03:51.4561417Z</Message></Error>.
Client-Request-ID=94630f57-67de-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Mon, 04 Jun 2018 10:03:50 GMT, Server-Request-ID=927dfdce-c01e-005c-44eb-fb70f1000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:927dfdce-c01e-005c-44eb-fb70f1000000Time:2018-06-04T10:03:51.6128141Z</Message></Error>.
Traceback (most recent call last):
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/site-packages/azureml/core/webservice/webservice.py", line 279, in _deploy_webservice
    resp.raise_for_status()
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://eastus2euap.modelmanagement.azureml.net/api/subscriptions/fac34303-435d-4486-8c3f-7094d82a0b60/resourceGroups/aml-notebooks/providers/Microsoft.MachineLearningServices/workspaces/haieastus2euapws/services?api-version=2018-03-01-preview

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./01.interactive.e2e.py", line 139, in <module>
    driver = 'score.py')
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/site-packages/azureml/core/workspace.py", line 787, in deploy_webservice
    return Webservice.deploy_from_image(self, name, image, deploy_config, target)
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/site-packages/azureml/core/webservice/webservice.py", line 241, in deploy_from_image
    return child._deploy(workspace, name, image, deployment_config)
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/site-packages/azureml/core/webservice/aci.py", line 108, in _deploy
    return Webservice._deploy_webservice(workspace, name, create_payload, AciWebservice)
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/site-packages/azureml/core/webservice/webservice.py", line 284, in _deploy_webservice
    'Content: {}'.format(resp.status_code, resp.headers, resp.content))
azureml.exceptions.azureml_exception.WebserviceException: Received bad response from Model Management Service:
Response Code: 409
Headers: {'Date': 'Mon, 04 Jun 2018 10:05:22 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'api-supported-versions': '2018-03-01-preview', 'x-ms-client-request-id': 'c2a2bed1d37240839876879e94b477c8', 'x-ms-client-session-id': '', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains; preload'}
Content: b'{"code":"Conflict","statusCode":409,"message":"Conflict","details":[{"code":"ServiceWithNameExists","message":"Workspace haieastus2euapws already contains a Service with name: rrs01a"}]}'
date: extra operand ‘%F-%T’
Try 'date --help' for more information.
Client-Request-ID=528248ee-67e3-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Mon, 04 Jun 2018 10:37:47 GMT, Server-Request-ID=63ba4e2d-801e-004d-59f0-fbea45000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:63ba4e2d-801e-004d-59f0-fbea45000000Time:2018-06-04T10:37:47.5366072Z</Message></Error>.
Client-Request-ID=528248f0-67e3-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Mon, 04 Jun 2018 10:37:47 GMT, Server-Request-ID=ae02aa3c-001e-006c-19f0-fbce3e000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:ae02aa3c-001e-006c-19f0-fbce3e000000Time:2018-06-04T10:37:47.6917278Z</Message></Error>.
Client-Request-ID=528248f2-67e3-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Mon, 04 Jun 2018 10:37:46 GMT, Server-Request-ID=cf763417-401e-000f-20f0-fb53c5000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:cf763417-401e-000f-20f0-fb53c5000000Time:2018-06-04T10:37:47.8481285Z</Message></Error>.
Client-Request-ID=528248f4-67e3-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Mon, 04 Jun 2018 10:37:47 GMT, Server-Request-ID=d0408c5a-101e-0070-40f0-fb9c5e000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:d0408c5a-101e-0070-40f0-fb9c5e000000Time:2018-06-04T10:37:48.0043372Z</Message></Error>.
Traceback (most recent call last):
  File "./10.o16n.py", line 88, in <module>
    model.delete()
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/site-packages/azureml/core/model.py", line 313, in delete
    'Content: {}'.format(resp.status_code, resp.headers, resp.content))
azureml.exceptions.azureml_exception.WebserviceException: Received bad response from Model Management Service:
Response Code: 412
Headers: {'Date': 'Mon, 04 Jun 2018 10:44:09 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'api-supported-versions': '2018-03-01-preview', 'x-ms-client-request-id': '9690f657a5494829969dbe3ecf15a1c5', 'x-ms-client-session-id': '', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains; preload'}
Content: b'{"code":"PreconditionFailed","statusCode":412,"message":"PreconditionFailed","details":[{"code":"DeletionRequired","message":"The model with id mymodel:1 can not be deleted because it is currently being used in one or more images"}]}'
Already on 'master'
