Switched to branch 'daily'
Client-Request-ID=b9aef5b5-6d5e-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Mon, 11 Jun 2018 10:03:45 GMT, Server-Request-ID=87f14b92-401e-001f-776b-0196ad000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:87f14b92-401e-001f-776b-0196ad000000Time:2018-06-11T10:03:45.1115053Z</Message></Error>.
Client-Request-ID=b9aef5b7-6d5e-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Mon, 11 Jun 2018 10:03:44 GMT, Server-Request-ID=9bb653da-001e-000e-306b-010c19000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:9bb653da-001e-000e-306b-010c19000000Time:2018-06-11T10:03:45.2708057Z</Message></Error>.
Client-Request-ID=b9aef5b9-6d5e-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Mon, 11 Jun 2018 10:03:44 GMT, Server-Request-ID=14a2bc0e-301e-003a-1c6b-013fd1000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:14a2bc0e-301e-003a-1c6b-013fd1000000Time:2018-06-11T10:03:45.4305967Z</Message></Error>.
Client-Request-ID=b9aef5bb-6d5e-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Mon, 11 Jun 2018 10:03:44 GMT, Server-Request-ID=88c7b510-f01e-0068-236b-014339000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:88c7b510-f01e-0068-236b-014339000000Time:2018-06-11T10:03:45.5921779Z</Message></Error>.
Traceback (most recent call last):
  File "./02.local.py", line 92, in <module>
    min(metrics['mse']), 
KeyError: 'mse'
Client-Request-ID=f4c9375a-6d62-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Mon, 11 Jun 2018 10:34:01 GMT, Server-Request-ID=5f6d7fb4-a01e-005a-416f-01434e000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:5f6d7fb4-a01e-005a-416f-01434e000000Time:2018-06-11T10:34:01.6897794Z</Message></Error>.
Client-Request-ID=f4c9375c-6d62-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Mon, 11 Jun 2018 10:34:01 GMT, Server-Request-ID=072c4866-d01e-000d-3e6f-01ed7d000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:072c4866-d01e-000d-3e6f-01ed7d000000Time:2018-06-11T10:34:01.8449141Z</Message></Error>.
Client-Request-ID=f4c9375e-6d62-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Mon, 11 Jun 2018 10:34:01 GMT, Server-Request-ID=31e2d125-001e-0043-2a6f-01c3f5000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:31e2d125-001e-0043-2a6f-01c3f5000000Time:2018-06-11T10:34:01.9991033Z</Message></Error>.
Client-Request-ID=f4c93760-6d62-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Mon, 11 Jun 2018 10:34:01 GMT, Server-Request-ID=8c94ead3-101e-0084-2d6f-0157a8000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:8c94ead3-101e-0084-2d6f-0157a8000000Time:2018-06-11T10:34:02.1525346Z</Message></Error>.
Traceback (most recent call last):
  File "./10.o16n.py", line 88, in <module>
    model.delete()
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/site-packages/azureml/core/model.py", line 313, in delete
    'Content: {}'.format(resp.status_code, resp.headers, resp.content))
azureml.exceptions.azureml_exception.WebserviceException: Received bad response from Model Management Service:
Response Code: 412
Headers: {'Date': 'Mon, 11 Jun 2018 10:41:30 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'api-supported-versions': '2018-03-01-preview', 'x-ms-client-request-id': 'bd2cb3d00bc548ab8567210261e5fff9', 'x-ms-client-session-id': '', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains; preload'}
Content: b'{"code":"PreconditionFailed","statusCode":412,"message":"PreconditionFailed","details":[{"code":"DeletionRequired","message":"The model with id mymodel:1 can not be deleted because it is currently being used in one or more images"}]}'
Switched to branch 'master'
