Switched to branch 'daily'
Client-Request-ID=2a1e401b-6d3d-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Mon, 11 Jun 2018 06:03:30 GMT, Server-Request-ID=52651548-901e-0023-5c49-01bf6a000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:52651548-901e-0023-5c49-01bf6a000000Time:2018-06-11T06:03:30.8618517Z</Message></Error>.
Client-Request-ID=2a1e401d-6d3d-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Mon, 11 Jun 2018 06:03:30 GMT, Server-Request-ID=e3e9f58c-d01e-001d-4249-012815000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:e3e9f58c-d01e-001d-4249-012815000000Time:2018-06-11T06:03:31.0181610Z</Message></Error>.
Client-Request-ID=2a1e401f-6d3d-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Mon, 11 Jun 2018 06:03:30 GMT, Server-Request-ID=7963994f-601e-006a-2849-01fd81000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:7963994f-601e-006a-2849-01fd81000000Time:2018-06-11T06:03:31.1748020Z</Message></Error>.
Client-Request-ID=2a1e4021-6d3d-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Mon, 11 Jun 2018 06:03:30 GMT, Server-Request-ID=a833d99b-301e-002a-7649-01fab9000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:a833d99b-301e-002a-7649-01fab9000000Time:2018-06-11T06:03:31.3313054Z</Message></Error>.
Traceback (most recent call last):
  File "./02.local.py", line 92, in <module>
    min(metrics['mse']), 
KeyError: 'mse'
Client-Request-ID=6d098764-6d41-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Mon, 11 Jun 2018 06:33:59 GMT, Server-Request-ID=9a853811-701e-0076-304e-01afe1000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:9a853811-701e-0076-304e-01afe1000000Time:2018-06-11T06:34:00.5537528Z</Message></Error>.
Client-Request-ID=6d098766-6d41-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Mon, 11 Jun 2018 06:34:00 GMT, Server-Request-ID=80fc3c1d-801e-005d-214e-012f2d000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:80fc3c1d-801e-005d-214e-012f2d000000Time:2018-06-11T06:34:00.7123327Z</Message></Error>.
Client-Request-ID=6d098768-6d41-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Mon, 11 Jun 2018 06:34:00 GMT, Server-Request-ID=5530eac5-401e-0042-1d4e-019c29000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:5530eac5-401e-0042-1d4e-019c29000000Time:2018-06-11T06:34:00.8692710Z</Message></Error>.
Client-Request-ID=6d09876a-6d41-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Mon, 11 Jun 2018 06:34:00 GMT, Server-Request-ID=33473cd1-301e-0077-5e4e-01f03d000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:33473cd1-301e-0077-5e4e-01f03d000000Time:2018-06-11T06:34:01.0246473Z</Message></Error>.
Traceback (most recent call last):
  File "./10.o16n.py", line 88, in <module>
    model.delete()
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/site-packages/azureml/core/model.py", line 313, in delete
    'Content: {}'.format(resp.status_code, resp.headers, resp.content))
azureml.exceptions.azureml_exception.WebserviceException: Received bad response from Model Management Service:
Response Code: 412
Headers: {'Date': 'Mon, 11 Jun 2018 06:40:46 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'api-supported-versions': '2018-03-01-preview', 'x-ms-client-request-id': 'cca5a8b9cecc4318b51abd2f11d80a49', 'x-ms-client-session-id': '', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains; preload'}
Content: b'{"code":"PreconditionFailed","statusCode":412,"message":"PreconditionFailed","details":[{"code":"DeletionRequired","message":"The model with id mymodel:1 can not be deleted because it is currently being used in one or more images"}]}'
Switched to branch 'master'
