Already on 'master'
Client-Request-ID=47f9bea0-6a29-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Thu, 07 Jun 2018 08:03:35 GMT, Server-Request-ID=b0a19412-b01e-00e0-3536-feb2b9000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:b0a19412-b01e-00e0-3536-feb2b9000000Time:2018-06-07T08:03:36.9625350Z</Message></Error>.
Client-Request-ID=47f9bea2-6a29-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Thu, 07 Jun 2018 08:03:37 GMT, Server-Request-ID=5c9d578a-301e-00d8-6a36-fef3e0000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:5c9d578a-301e-00d8-6a36-fef3e0000000Time:2018-06-07T08:03:37.5219116Z</Message></Error>.
Client-Request-ID=47f9bea4-6a29-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Thu, 07 Jun 2018 08:03:37 GMT, Server-Request-ID=2c8a5c80-501e-0062-6936-fe13e9000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:2c8a5c80-501e-0062-6936-fe13e9000000Time:2018-06-07T08:03:37.7271058Z</Message></Error>.
Client-Request-ID=47f9bea6-6a29-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Thu, 07 Jun 2018 08:03:37 GMT, Server-Request-ID=d1646329-501e-000f-7b36-feb9c7000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:d1646329-501e-000f-7b36-feb9c7000000Time:2018-06-07T08:03:37.9189602Z</Message></Error>.
Client-Request-ID=47f9bea8-6a29-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Thu, 07 Jun 2018 08:03:37 GMT, Server-Request-ID=5265067c-d01e-0078-0836-fe3c86000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:5265067c-d01e-0078-0836-fe3c86000000Time:2018-06-07T08:03:38.1197511Z</Message></Error>.
Traceback (most recent call last):
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/site-packages/azureml/core/webservice/webservice.py", line 281, in _deploy_webservice
    resp.raise_for_status()
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://eastus2.modelmanagement.azureml.net/api/subscriptions/fac34303-435d-4486-8c3f-7094d82a0b60/resourceGroups/aml-notebooks/providers/Microsoft.MachineLearningServices/workspaces/haieastus2ws3/services?api-version=2018-03-01-preview

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./01.interactive.e2e.py", line 139, in <module>
    driver = 'score.py')
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/site-packages/azureml/core/workspace.py", line 819, in deploy_webservice
    return Webservice.deploy_from_image(self, name, image, deploy_config, target)
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/site-packages/azureml/core/webservice/webservice.py", line 242, in deploy_from_image
    return child._deploy(workspace, name, image, deployment_config)
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/site-packages/azureml/core/webservice/aci.py", line 109, in _deploy
    return Webservice._deploy_webservice(workspace, name, create_payload, AciWebservice)
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/site-packages/azureml/core/webservice/webservice.py", line 286, in _deploy_webservice
    'Content: {}'.format(resp.status_code, resp.headers, resp.content))
azureml.exceptions.azureml_exception.WebserviceException: Received bad response from Model Management Service:
Response Code: 409
Headers: {'Date': 'Thu, 07 Jun 2018 08:05:29 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'api-supported-versions': '2018-03-01-preview', 'x-ms-client-request-id': 'dde13a83e5504a50b4cd5cacb0909c02', 'x-ms-client-session-id': '', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains; preload'}
Content: b'{"code":"Conflict","statusCode":409,"message":"Conflict","details":[{"code":"ServiceWithNameExists","message":"Workspace haieastus2ws3 already contains a Service with name: rrs01a"}]}'
Client-Request-ID=59dfce70-6a2e-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Thu, 07 Jun 2018 08:39:54 GMT, Server-Request-ID=19fd796f-001e-009f-563b-fe2c8b000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:19fd796f-001e-009f-563b-fe2c8b000000Time:2018-06-07T08:39:54.4776090Z</Message></Error>.
Client-Request-ID=5ae2e6f4-6a2e-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Thu, 07 Jun 2018 08:39:55 GMT, Server-Request-ID=ad58baae-a01e-00ff-0e3b-fe69a9000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:ad58baae-a01e-00ff-0e3b-fe69a9000000Time:2018-06-07T08:39:56.1751566Z</Message></Error>.
Client-Request-ID=5ae2e6f6-6a2e-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Thu, 07 Jun 2018 08:39:56 GMT, Server-Request-ID=97700233-c01e-0089-2d3b-feed15000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:97700233-c01e-0089-2d3b-feed15000000Time:2018-06-07T08:39:56.3364650Z</Message></Error>.
Client-Request-ID=5ae2e6f8-6a2e-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Thu, 07 Jun 2018 08:39:56 GMT, Server-Request-ID=a8f83295-201e-0022-723b-fe3a07000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:a8f83295-201e-0022-723b-fe3a07000000Time:2018-06-07T08:39:56.4990164Z</Message></Error>.
Client-Request-ID=5ae2e6fa-6a2e-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Thu, 07 Jun 2018 08:39:55 GMT, Server-Request-ID=a47363a5-f01e-006f-613b-fefce5000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:a47363a5-f01e-006f-613b-fefce5000000Time:2018-06-07T08:39:56.6688214Z</Message></Error>.
Traceback (most recent call last):
  File "./10.o16n.py", line 89, in <module>
    model.delete()
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/site-packages/azureml/core/model.py", line 300, in delete
    'Content: {}'.format(resp.status_code, resp.headers, resp.content))
azureml.exceptions.azureml_exception.WebserviceException: Received bad response from Model Management Service:
Response Code: 412
Headers: {'Date': 'Thu, 07 Jun 2018 08:47:14 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'api-supported-versions': '2018-03-01-preview', 'x-ms-client-request-id': '8babedc3a5e14a2db358c03a164f08ec', 'x-ms-client-session-id': '', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains; preload'}
Content: b'{"code":"PreconditionFailed","statusCode":412,"message":"PreconditionFailed","details":[{"code":"DeletionRequired","message":"The model with id mymodel:26 can not be deleted because it is currently being used in one or more images"}]}'
Already on 'master'
