Switched to branch 'candidate'
Client-Request-ID=62c23beb-6b5f-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Fri, 08 Jun 2018 21:03:25 GMT, Server-Request-ID=90be08be-501e-00c8-266c-ffc506000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:90be08be-501e-00c8-266c-ffc506000000Time:2018-06-08T21:03:26.5030685Z</Message></Error>.
Client-Request-ID=62c23bed-6b5f-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Fri, 08 Jun 2018 21:03:26 GMT, Server-Request-ID=b5279033-a01e-00d6-536c-ff1feb000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:b5279033-a01e-00d6-536c-ff1feb000000Time:2018-06-08T21:03:26.6709120Z</Message></Error>.
Client-Request-ID=62c23bef-6b5f-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Fri, 08 Jun 2018 21:03:26 GMT, Server-Request-ID=1ba0307f-601e-0025-1a6c-ffcc82000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:1ba0307f-601e-0025-1a6c-ffcc82000000Time:2018-06-08T21:03:26.8674817Z</Message></Error>.
Client-Request-ID=62c23bf1-6b5f-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Fri, 08 Jun 2018 21:03:26 GMT, Server-Request-ID=37f68756-b01e-000e-7b6c-ffb83a000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:37f68756-b01e-000e-7b6c-ffb83a000000Time:2018-06-08T21:03:27.0569091Z</Message></Error>.
Traceback (most recent call last):
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azureml/core/webservice/webservice.py", line 291, in _deploy_webservice
    resp.raise_for_status()
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://eastus2.modelmanagement.azureml.net/api/subscriptions/fac34303-435d-4486-8c3f-7094d82a0b60/resourceGroups/aml-notebooks/providers/Microsoft.MachineLearningServices/workspaces/haieastus2ws3/services?api-version=2018-03-01-preview

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./01.interactive.e2e.py", line 139, in <module>
    driver = 'score.py')
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azureml/core/workspace.py", line 787, in deploy_webservice
    return Webservice.deploy_from_image(self, name, image, deploy_config, target)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azureml/core/webservice/webservice.py", line 253, in deploy_from_image
    return child._deploy(workspace, name, image, deployment_config)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azureml/core/webservice/aci.py", line 108, in _deploy
    return Webservice._deploy_webservice(workspace, name, create_payload, AciWebservice)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azureml/core/webservice/webservice.py", line 296, in _deploy_webservice
    'Content: {}'.format(resp.status_code, resp.headers, resp.content))
azureml.exceptions.azureml_exception.WebserviceException: Received bad response from Model Management Service:
Response Code: 409
Headers: {'Date': 'Fri, 08 Jun 2018 21:04:57 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'api-supported-versions': '2018-03-01-preview', 'x-ms-client-request-id': '67d3e34a559d4a20ad1da835d1f04a57', 'x-ms-client-session-id': '', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains; preload'}
Content: b'{"code":"Conflict","statusCode":409,"message":"Conflict","details":[{"code":"ServiceWithNameExists","message":"Workspace haieastus2ws3 already contains a Service with name: rrs01a"}]}'
Client-Request-ID=ba903153-6b63-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Fri, 08 Jun 2018 21:34:32 GMT, Server-Request-ID=114aec6e-901e-007f-7770-ffca03000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:114aec6e-901e-007f-7770-ffca03000000Time:2018-06-08T21:34:32.4015089Z</Message></Error>.
Client-Request-ID=ba903155-6b63-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Fri, 08 Jun 2018 21:34:32 GMT, Server-Request-ID=d0a69997-701e-0090-0e70-ffc17d000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:d0a69997-701e-0090-0e70-ffc17d000000Time:2018-06-08T21:34:32.6022262Z</Message></Error>.
Client-Request-ID=ba903157-6b63-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Fri, 08 Jun 2018 21:34:32 GMT, Server-Request-ID=0c26d9a4-301e-003d-4170-ffe117000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:0c26d9a4-301e-003d-4170-ffe117000000Time:2018-06-08T21:34:32.7660328Z</Message></Error>.
Client-Request-ID=ba903159-6b63-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Fri, 08 Jun 2018 21:34:32 GMT, Server-Request-ID=93d5736e-d01e-0111-3670-ff257f000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:93d5736e-d01e-0111-3670-ff257f000000Time:2018-06-08T21:34:32.9471867Z</Message></Error>.
Traceback (most recent call last):
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azureml/core/webservice/webservice.py", line 291, in _deploy_webservice
    resp.raise_for_status()
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://eastus2.modelmanagement.azureml.net/api/subscriptions/fac34303-435d-4486-8c3f-7094d82a0b60/resourceGroups/aml-notebooks/providers/Microsoft.MachineLearningServices/workspaces/haieastus2ws3/services?api-version=2018-03-01-preview

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./10.o16n.py", line 64, in <module>
    image = image)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azureml/core/workspace.py", line 787, in deploy_webservice
    return Webservice.deploy_from_image(self, name, image, deploy_config, target)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azureml/core/webservice/webservice.py", line 253, in deploy_from_image
    return child._deploy(workspace, name, image, deployment_config)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azureml/core/webservice/aci.py", line 108, in _deploy
    return Webservice._deploy_webservice(workspace, name, create_payload, AciWebservice)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azureml/core/webservice/webservice.py", line 296, in _deploy_webservice
    'Content: {}'.format(resp.status_code, resp.headers, resp.content))
azureml.exceptions.azureml_exception.WebserviceException: Received bad response from Model Management Service:
Response Code: 409
Headers: {'Date': 'Fri, 08 Jun 2018 21:36:31 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'api-supported-versions': '2018-03-01-preview', 'x-ms-client-request-id': '52dc94eb1d684523b53a4db18910c740', 'x-ms-client-session-id': '', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains; preload'}
Content: b'{"code":"Conflict","statusCode":409,"message":"Conflict","details":[{"code":"ServiceWithNameExists","message":"Workspace haieastus2ws3 already contains a Service with name: rrs02"}]}'
error: Your local changes to the following files would be overwritten by checkout:
	e2e_test/aml_config/config.json
	e2e_test/best_model.pkl
	e2e_test/mse_over_alpha.png
Please, commit your changes or stash them before you can switch branches.
Aborting
