error: pathspec 'daily' did not match any file(s) known to git.
Client-Request-ID=f7b1fe27-67bc-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Mon, 04 Jun 2018 06:03:14 GMT, Server-Request-ID=9b7b7f90-101e-0060-63c9-fb5936000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:9b7b7f90-101e-0060-63c9-fb5936000000Time:2018-06-04T06:03:15.5856155Z</Message></Error>.
Client-Request-ID=f7b1fe29-67bc-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Mon, 04 Jun 2018 06:03:14 GMT, Server-Request-ID=b3b71491-f01e-0025-71c9-fb8cd5000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:b3b71491-f01e-0025-71c9-fb8cd5000000Time:2018-06-04T06:03:15.7465856Z</Message></Error>.
Client-Request-ID=f7b1fe2b-67bc-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Mon, 04 Jun 2018 06:03:15 GMT, Server-Request-ID=27115f0a-a01e-0075-55c9-fb4e85000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:27115f0a-a01e-0075-55c9-fb4e85000000Time:2018-06-04T06:03:15.9013590Z</Message></Error>.
Client-Request-ID=f7b1fe2d-67bc-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Mon, 04 Jun 2018 06:03:15 GMT, Server-Request-ID=5b83037f-d01e-0022-2ac9-fbe0b6000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:5b83037f-d01e-0022-2ac9-fbe0b6000000Time:2018-06-04T06:03:16.0580282Z</Message></Error>.
Traceback (most recent call last):
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/site-packages/azureml/core/webservice/webservice.py", line 279, in _deploy_webservice
    resp.raise_for_status()
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://eastus2euap.modelmanagement.azureml.net/api/subscriptions/fac34303-435d-4486-8c3f-7094d82a0b60/resourceGroups/aml-notebooks/providers/Microsoft.MachineLearningServices/workspaces/haieastus2euapws/services?api-version=2018-03-01-preview

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./01.interactive.e2e.py", line 139, in <module>
    driver = 'score.py')
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/site-packages/azureml/core/workspace.py", line 787, in deploy_webservice
    return Webservice.deploy_from_image(self, name, image, deploy_config, target)
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/site-packages/azureml/core/webservice/webservice.py", line 241, in deploy_from_image
    return child._deploy(workspace, name, image, deployment_config)
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/site-packages/azureml/core/webservice/aci.py", line 108, in _deploy
    return Webservice._deploy_webservice(workspace, name, create_payload, AciWebservice)
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/site-packages/azureml/core/webservice/webservice.py", line 284, in _deploy_webservice
    'Content: {}'.format(resp.status_code, resp.headers, resp.content))
azureml.exceptions.azureml_exception.WebserviceException: Received bad response from Model Management Service:
Response Code: 409
Headers: {'Date': 'Mon, 04 Jun 2018 06:04:40 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'api-supported-versions': '2018-03-01-preview', 'x-ms-client-request-id': '9124eb46c8534be3a5baa82e9fb0fe20', 'x-ms-client-session-id': '', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains; preload'}
Content: b'{"code":"Conflict","statusCode":409,"message":"Conflict","details":[{"code":"ServiceWithNameExists","message":"Workspace haieastus2euapws already contains a Service with name: rrs01a"}]}'
date: extra operand ‘%F-%T’
Try 'date --help' for more information.
Client-Request-ID=b791667f-67c1-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Mon, 04 Jun 2018 06:37:15 GMT, Server-Request-ID=6fa634a8-601e-007a-3ace-fb38e9000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:6fa634a8-601e-007a-3ace-fb38e9000000Time:2018-06-04T06:37:15.6487541Z</Message></Error>.
Client-Request-ID=b7916681-67c1-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Mon, 04 Jun 2018 06:37:15 GMT, Server-Request-ID=6f451942-f01e-0035-6ace-fb49bd000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:6f451942-f01e-0035-6ace-fb49bd000000Time:2018-06-04T06:37:15.8056462Z</Message></Error>.
Client-Request-ID=b7916683-67c1-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Mon, 04 Jun 2018 06:37:15 GMT, Server-Request-ID=7736b57c-401e-0030-73ce-fb9b66000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:7736b57c-401e-0030-73ce-fb9b66000000Time:2018-06-04T06:37:15.9625738Z</Message></Error>.
Client-Request-ID=b8b61482-67c1-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Mon, 04 Jun 2018 06:37:15 GMT, Server-Request-ID=a0e1bf83-b01e-0046-3cce-fb112e000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:a0e1bf83-b01e-0046-3cce-fb112e000000Time:2018-06-04T06:37:16.1200888Z</Message></Error>.
Traceback (most recent call last):
  File "./10.o16n.py", line 88, in <module>
    model.delete()
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/site-packages/azureml/core/model.py", line 313, in delete
    'Content: {}'.format(resp.status_code, resp.headers, resp.content))
azureml.exceptions.azureml_exception.WebserviceException: Received bad response from Model Management Service:
Response Code: 412
Headers: {'Date': 'Mon, 04 Jun 2018 06:44:41 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'api-supported-versions': '2018-03-01-preview', 'x-ms-client-request-id': '5e6fd429a338488bb8d98693b3fe91c6', 'x-ms-client-session-id': '', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains; preload'}
Content: b'{"code":"PreconditionFailed","statusCode":412,"message":"PreconditionFailed","details":[{"code":"DeletionRequired","message":"The model with id mymodel:1 can not be deleted because it is currently being used in one or more images"}]}'
Already on 'master'
