Already on 'master'
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Client-Request-ID=24ee2ed4-7094-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Fri, 15 Jun 2018 12:03:40 GMT, Server-Request-ID=7c9341ed-e01e-0051-3da0-044591000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:7c9341ed-e01e-0051-3da0-044591000000Time:2018-06-15T12:03:41.2976639Z</Message></Error>.
Client-Request-ID=24ee2ed6-7094-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Fri, 15 Jun 2018 12:03:40 GMT, Server-Request-ID=e9c01cb9-c01e-0106-2ba0-04ea49000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:e9c01cb9-c01e-0106-2ba0-04ea49000000Time:2018-06-15T12:03:41.4657048Z</Message></Error>.
Client-Request-ID=24ee2ed8-7094-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Fri, 15 Jun 2018 12:03:40 GMT, Server-Request-ID=963865be-d01e-00f3-69a0-04880d000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:963865be-d01e-00f3-69a0-04880d000000Time:2018-06-15T12:03:41.6329252Z</Message></Error>.
Client-Request-ID=24ee2eda-7094-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Fri, 15 Jun 2018 12:03:41 GMT, Server-Request-ID=4fb44da9-401e-0018-5ba0-0476f1000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:4fb44da9-401e-0018-5ba0-0476f1000000Time:2018-06-15T12:03:41.8051240Z</Message></Error>.
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Traceback (most recent call last):
  File "./02.local.py", line 51, in <module>
    script_to_run = train_script)
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/site-packages/azureml/core/run.py", line 66, in submit
    execute_with_zip=_execute_with_zip)
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/site-packages/azureml/execution/_commands.py", line 110, in start_run
    telemetry_values=telemetry_values)
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/site-packages/azureml/execution/_commands.py", line 272, in _start_internal_local_cloud
    snapshot_id = snapshot_async.get()
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/site-packages/azureml/base_sdk_common/create_snapshot.py", line 102, in create_snapshot
    raise ExperimentExecutionException(get_http_exception_response_string(response))
azureml.exceptions.azureml_exception.ExperimentExecutionException: {
    "url": "https://eastus2.experiments.azureml.net/content/v1.0/subscriptions/fac34303-435d-4486-8c3f-7094d82a0b60/resourceGroups/aml-notebooks/providers/Microsoft.MachineLearningServices/workspaces/haieastus2ws3/snapshots/cdf14b70-e423-47a8-930c-961b729ba798?parentSnapshotId=2bd3167f-0978-42bd-9795-6c89fc1e31b2",
    "status_code": 404,
    "text": "{\n  \"error\": {\n    \"code\": \"UserError\",\n    \"message\": \"Unable to find snapshot with id: 2bd3167f-0978-42bd-9795-6c89fc1e31b2\",\n    \"target\": null,\n    \"details\": [],\n    \"innerError\": null,\n    \"debugInfo\": {\n      \"type\": \"Common.WebApi.Exceptions.ResourceNotFoundException\",\n      \"message\": \"Unable to find snapshot with id: 2bd3167f-0978-42bd-9795-6c89fc1e31b2\",\n      \"stackTrace\": \"   at Microsoft.MachineLearning.Project.Services.SnapshotStore.<GetBlobAsStringOrFailNotFound>d__17.MoveNext() in /opt/vsts/work/1/s/src/azureml-api/src/ProjectContent/Services/SnapshotStore.cs:line 271\\n--- End of stack trace from previous location where exception was thrown ---\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\n   at Microsoft.MachineLearning.Project.Services.SnapshotStore.<GetSnapshot>d__7.MoveNext() in /opt/vsts/work/1/s/src/azureml-api/src/ProjectContent/Services/SnapshotStore.cs:line 113\\n--- End of stack trace from previous location where exception was thrown ---\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\n   at Microsoft.MachineLearning.ProjectContent.EntryPoints.Controllers.SnapshotController.<CreateSnapshot>d__12.MoveNext() in /opt/vsts/work/1/s/src/azureml-api/src/ProjectContent/EntryPoints/Controllers/SnapshotController.cs:line 212\\n--- End of stack trace from previous location where exception was thrown ---\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()\\n--- End of stack trace from previous location where exception was thrown ---\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\\n--- End of stack trace from previous location where exception was thrown ---\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\\n--- End of stack trace from previous location where exception was thrown ---\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()\",\n      \"innerException\": null,\n      \"data\": {},\n      \"errorResponse\": null\n    }\n  },\n  \"correlation\": {\n    \"operation\": \"70e807b6-4fa154d2e7b3b1f2\",\n    \"request\": \"BLZinNnCdm8=\"\n  }\n}"
}
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Traceback (most recent call last):
  File "./03.aci.py", line 85, in <module>
    script_to_run = train_script)
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/site-packages/azureml/core/run.py", line 66, in submit
    execute_with_zip=_execute_with_zip)
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/site-packages/azureml/execution/_commands.py", line 116, in start_run
    execute_with_zip=execute_with_zip)
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/site-packages/azureml/execution/_commands.py", line 365, in _start_internal
    snapshot_id = snapshot_async.get()
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/site-packages/azureml/base_sdk_common/create_snapshot.py", line 102, in create_snapshot
    raise ExperimentExecutionException(get_http_exception_response_string(response))
azureml.exceptions.azureml_exception.ExperimentExecutionException: {
    "url": "https://eastus2.experiments.azureml.net/content/v1.0/subscriptions/fac34303-435d-4486-8c3f-7094d82a0b60/resourceGroups/aml-notebooks/providers/Microsoft.MachineLearningServices/workspaces/haieastus2ws3/snapshots/2091a504-1df4-43be-963c-72d59a6175f4?parentSnapshotId=b8317c26-6671-44a6-9859-67a0a7be6afa",
    "status_code": 404,
    "text": "{\n  \"error\": {\n    \"code\": \"UserError\",\n    \"message\": \"Unable to find snapshot with id: b8317c26-6671-44a6-9859-67a0a7be6afa\",\n    \"target\": null,\n    \"details\": [],\n    \"innerError\": null,\n    \"debugInfo\": {\n      \"type\": \"Common.WebApi.Exceptions.ResourceNotFoundException\",\n      \"message\": \"Unable to find snapshot with id: b8317c26-6671-44a6-9859-67a0a7be6afa\",\n      \"stackTrace\": \"   at Microsoft.MachineLearning.Project.Services.SnapshotStore.<GetBlobAsStringOrFailNotFound>d__17.MoveNext() in /opt/vsts/work/1/s/src/azureml-api/src/ProjectContent/Services/SnapshotStore.cs:line 271\\n--- End of stack trace from previous location where exception was thrown ---\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\n   at Microsoft.MachineLearning.Project.Services.SnapshotStore.<GetSnapshot>d__7.MoveNext() in /opt/vsts/work/1/s/src/azureml-api/src/ProjectContent/Services/SnapshotStore.cs:line 113\\n--- End of stack trace from previous location where exception was thrown ---\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\n   at Microsoft.MachineLearning.ProjectContent.EntryPoints.Controllers.SnapshotController.<CreateSnapshot>d__12.MoveNext() in /opt/vsts/work/1/s/src/azureml-api/src/ProjectContent/EntryPoints/Controllers/SnapshotController.cs:line 212\\n--- End of stack trace from previous location where exception was thrown ---\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()\\n--- End of stack trace from previous location where exception was thrown ---\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\\n--- End of stack trace from previous location where exception was thrown ---\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\\n--- End of stack trace from previous location where exception was thrown ---\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()\",\n      \"innerException\": null,\n      \"data\": {},\n      \"errorResponse\": null\n    }\n  },\n  \"correlation\": {\n    \"operation\": \"e8794bc9-4dafe5d5581f0658\",\n    \"request\": \"R58fPiivZhA=\"\n  }\n}"
}
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Traceback (most recent call last):
  File "./04.dsvm.py", line 70, in <module>
    script_to_run = train_script)
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/site-packages/azureml/core/run.py", line 66, in submit
    execute_with_zip=_execute_with_zip)
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/site-packages/azureml/execution/_commands.py", line 116, in start_run
    execute_with_zip=execute_with_zip)
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/site-packages/azureml/execution/_commands.py", line 365, in _start_internal
    snapshot_id = snapshot_async.get()
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/site-packages/azureml/base_sdk_common/create_snapshot.py", line 102, in create_snapshot
    raise ExperimentExecutionException(get_http_exception_response_string(response))
azureml.exceptions.azureml_exception.ExperimentExecutionException: {
    "url": "https://eastus2.experiments.azureml.net/content/v1.0/subscriptions/fac34303-435d-4486-8c3f-7094d82a0b60/resourceGroups/aml-notebooks/providers/Microsoft.MachineLearningServices/workspaces/haieastus2ws3/snapshots/7520fa8b-15f0-4eb1-b380-e9586bf0b78a?parentSnapshotId=4eb7d8fa-4b2e-4c7c-99cc-37dd5695023d",
    "status_code": 404,
    "text": "{\n  \"error\": {\n    \"code\": \"UserError\",\n    \"message\": \"Unable to find snapshot with id: 4eb7d8fa-4b2e-4c7c-99cc-37dd5695023d\",\n    \"target\": null,\n    \"details\": [],\n    \"innerError\": null,\n    \"debugInfo\": {\n      \"type\": \"Common.WebApi.Exceptions.ResourceNotFoundException\",\n      \"message\": \"Unable to find snapshot with id: 4eb7d8fa-4b2e-4c7c-99cc-37dd5695023d\",\n      \"stackTrace\": \"   at Microsoft.MachineLearning.Project.Services.SnapshotStore.<GetBlobAsStringOrFailNotFound>d__17.MoveNext() in /opt/vsts/work/1/s/src/azureml-api/src/ProjectContent/Services/SnapshotStore.cs:line 271\\n--- End of stack trace from previous location where exception was thrown ---\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\n   at Microsoft.MachineLearning.Project.Services.SnapshotStore.<GetSnapshot>d__7.MoveNext() in /opt/vsts/work/1/s/src/azureml-api/src/ProjectContent/Services/SnapshotStore.cs:line 113\\n--- End of stack trace from previous location where exception was thrown ---\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\n   at Microsoft.MachineLearning.ProjectContent.EntryPoints.Controllers.SnapshotController.<CreateSnapshot>d__12.MoveNext() in /opt/vsts/work/1/s/src/azureml-api/src/ProjectContent/EntryPoints/Controllers/SnapshotController.cs:line 212\\n--- End of stack trace from previous location where exception was thrown ---\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()\\n--- End of stack trace from previous location where exception was thrown ---\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\\n--- End of stack trace from previous location where exception was thrown ---\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\\n--- End of stack trace from previous location where exception was thrown ---\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()\",\n      \"innerException\": null,\n      \"data\": {},\n      \"errorResponse\": null\n    }\n  },\n  \"correlation\": {\n    \"operation\": \"48b7a246-4152fc13217d2006\",\n    \"request\": \"2wWPqY7Q6yc=\"\n  }\n}"
}
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Traceback (most recent call last):
  File "./05.spark.py", line 81, in <module>
    script_to_run = "train-spark.py")
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/site-packages/azureml/core/run.py", line 66, in submit
    execute_with_zip=_execute_with_zip)
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/site-packages/azureml/execution/_commands.py", line 116, in start_run
    execute_with_zip=execute_with_zip)
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/site-packages/azureml/execution/_commands.py", line 365, in _start_internal
    snapshot_id = snapshot_async.get()
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/site-packages/azureml/base_sdk_common/create_snapshot.py", line 102, in create_snapshot
    raise ExperimentExecutionException(get_http_exception_response_string(response))
azureml.exceptions.azureml_exception.ExperimentExecutionException: {
    "url": "https://eastus2.experiments.azureml.net/content/v1.0/subscriptions/fac34303-435d-4486-8c3f-7094d82a0b60/resourceGroups/aml-notebooks/providers/Microsoft.MachineLearningServices/workspaces/haieastus2ws3/snapshots/75314fcd-0fd0-480a-88ec-0c4a273542ab?parentSnapshotId=e9c619a7-7486-4eb3-8e27-4efdb021ec32",
    "status_code": 404,
    "text": "{\n  \"error\": {\n    \"code\": \"UserError\",\n    \"message\": \"Unable to find snapshot with id: e9c619a7-7486-4eb3-8e27-4efdb021ec32\",\n    \"target\": null,\n    \"details\": [],\n    \"innerError\": null,\n    \"debugInfo\": {\n      \"type\": \"Common.WebApi.Exceptions.ResourceNotFoundException\",\n      \"message\": \"Unable to find snapshot with id: e9c619a7-7486-4eb3-8e27-4efdb021ec32\",\n      \"stackTrace\": \"   at Microsoft.MachineLearning.Project.Services.SnapshotStore.<GetBlobAsStringOrFailNotFound>d__17.MoveNext() in /opt/vsts/work/1/s/src/azureml-api/src/ProjectContent/Services/SnapshotStore.cs:line 271\\n--- End of stack trace from previous location where exception was thrown ---\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\n   at Microsoft.MachineLearning.Project.Services.SnapshotStore.<GetSnapshot>d__7.MoveNext() in /opt/vsts/work/1/s/src/azureml-api/src/ProjectContent/Services/SnapshotStore.cs:line 113\\n--- End of stack trace from previous location where exception was thrown ---\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\n   at Microsoft.MachineLearning.ProjectContent.EntryPoints.Controllers.SnapshotController.<CreateSnapshot>d__12.MoveNext() in /opt/vsts/work/1/s/src/azureml-api/src/ProjectContent/EntryPoints/Controllers/SnapshotController.cs:line 212\\n--- End of stack trace from previous location where exception was thrown ---\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()\\n--- End of stack trace from previous location where exception was thrown ---\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\\n--- End of stack trace from previous location where exception was thrown ---\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\\n--- End of stack trace from previous location where exception was thrown ---\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()\",\n      \"innerException\": null,\n      \"data\": {},\n      \"errorResponse\": null\n    }\n  },\n  \"correlation\": {\n    \"operation\": \"35140d9-422e9e60cd6d6304\",\n    \"request\": \"4p58EsQDqFI=\"\n  }\n}"
}
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Traceback (most recent call last):
  File "./07.sklearn.hd.py", line 88, in <module>
    run = sk_est.fit()
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/site-packages/azureml/train/estimator.py", line 438, in fit
    return super(Estimator, self).fit()
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/site-packages/azureml/train/estimator.py", line 78, in fit
    _telemetry_values=telemetry_values)
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/site-packages/azureml/core/run.py", line 66, in submit
    execute_with_zip=_execute_with_zip)
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/site-packages/azureml/execution/_commands.py", line 116, in start_run
    execute_with_zip=execute_with_zip)
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/site-packages/azureml/execution/_commands.py", line 365, in _start_internal
    snapshot_id = snapshot_async.get()
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/site-packages/azureml/base_sdk_common/create_snapshot.py", line 102, in create_snapshot
    raise ExperimentExecutionException(get_http_exception_response_string(response))
azureml.exceptions.azureml_exception.ExperimentExecutionException: {
    "url": "https://eastus2.experiments.azureml.net/content/v1.0/subscriptions/fac34303-435d-4486-8c3f-7094d82a0b60/resourceGroups/aml-notebooks/providers/Microsoft.MachineLearningServices/workspaces/haieastus2ws3/snapshots/b4f7be88-f419-49cf-86f5-18ae415cf63a?parentSnapshotId=87311c3d-6b5f-4da6-a9ad-6d027c1096bc",
    "status_code": 404,
    "text": "{\n  \"error\": {\n    \"code\": \"UserError\",\n    \"message\": \"Unable to find snapshot with id: 87311c3d-6b5f-4da6-a9ad-6d027c1096bc\",\n    \"target\": null,\n    \"details\": [],\n    \"innerError\": null,\n    \"debugInfo\": {\n      \"type\": \"Common.WebApi.Exceptions.ResourceNotFoundException\",\n      \"message\": \"Unable to find snapshot with id: 87311c3d-6b5f-4da6-a9ad-6d027c1096bc\",\n      \"stackTrace\": \"   at Microsoft.MachineLearning.Project.Services.SnapshotStore.<GetBlobAsStringOrFailNotFound>d__17.MoveNext() in /opt/vsts/work/1/s/src/azureml-api/src/ProjectContent/Services/SnapshotStore.cs:line 271\\n--- End of stack trace from previous location where exception was thrown ---\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\n   at Microsoft.MachineLearning.Project.Services.SnapshotStore.<GetSnapshot>d__7.MoveNext() in /opt/vsts/work/1/s/src/azureml-api/src/ProjectContent/Services/SnapshotStore.cs:line 113\\n--- End of stack trace from previous location where exception was thrown ---\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\n   at Microsoft.MachineLearning.ProjectContent.EntryPoints.Controllers.SnapshotController.<CreateSnapshot>d__12.MoveNext() in /opt/vsts/work/1/s/src/azureml-api/src/ProjectContent/EntryPoints/Controllers/SnapshotController.cs:line 212\\n--- End of stack trace from previous location where exception was thrown ---\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()\\n--- End of stack trace from previous location where exception was thrown ---\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\\n--- End of stack trace from previous location where exception was thrown ---\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\\n--- End of stack trace from previous location where exception was thrown ---\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()\",\n      \"innerException\": null,\n      \"data\": {},\n      \"errorResponse\": null\n    }\n  },\n  \"correlation\": {\n    \"operation\": \"e8794bd2-4dafe5d5581f0658\",\n    \"request\": \"ALlUxLdsMpc=\"\n  }\n}"
}
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Traceback (most recent call last):
  File "./08.tf.hd.py", line 92, in <module>
    run = tfe.fit()
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/site-packages/azureml/train/dnn.py", line 320, in fit
    return super(TensorFlow, self).fit()
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/site-packages/azureml/train/estimator.py", line 78, in fit
    _telemetry_values=telemetry_values)
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/site-packages/azureml/core/run.py", line 66, in submit
    execute_with_zip=_execute_with_zip)
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/site-packages/azureml/execution/_commands.py", line 116, in start_run
    execute_with_zip=execute_with_zip)
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/site-packages/azureml/execution/_commands.py", line 365, in _start_internal
    snapshot_id = snapshot_async.get()
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/ninghai/miniconda3/envs/preview/lib/python3.6/site-packages/azureml/base_sdk_common/create_snapshot.py", line 102, in create_snapshot
    raise ExperimentExecutionException(get_http_exception_response_string(response))
azureml.exceptions.azureml_exception.ExperimentExecutionException: {
    "url": "https://eastus2.experiments.azureml.net/content/v1.0/subscriptions/fac34303-435d-4486-8c3f-7094d82a0b60/resourceGroups/aml-notebooks/providers/Microsoft.MachineLearningServices/workspaces/haieastus2ws3/snapshots/26c4cd1e-7cf8-4424-8dfa-d573df2678b0?parentSnapshotId=f2407d9f-2238-46f6-92ce-8f95174e96e7",
    "status_code": 404,
    "text": "{\n  \"error\": {\n    \"code\": \"UserError\",\n    \"message\": \"Unable to find snapshot with id: f2407d9f-2238-46f6-92ce-8f95174e96e7\",\n    \"target\": null,\n    \"details\": [],\n    \"innerError\": null,\n    \"debugInfo\": {\n      \"type\": \"Common.WebApi.Exceptions.ResourceNotFoundException\",\n      \"message\": \"Unable to find snapshot with id: f2407d9f-2238-46f6-92ce-8f95174e96e7\",\n      \"stackTrace\": \"   at Microsoft.MachineLearning.Project.Services.SnapshotStore.<GetBlobAsStringOrFailNotFound>d__17.MoveNext() in /opt/vsts/work/1/s/src/azureml-api/src/ProjectContent/Services/SnapshotStore.cs:line 271\\n--- End of stack trace from previous location where exception was thrown ---\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\n   at Microsoft.MachineLearning.Project.Services.SnapshotStore.<GetSnapshot>d__7.MoveNext() in /opt/vsts/work/1/s/src/azureml-api/src/ProjectContent/Services/SnapshotStore.cs:line 113\\n--- End of stack trace from previous location where exception was thrown ---\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\n   at Microsoft.MachineLearning.ProjectContent.EntryPoints.Controllers.SnapshotController.<CreateSnapshot>d__12.MoveNext() in /opt/vsts/work/1/s/src/azureml-api/src/ProjectContent/EntryPoints/Controllers/SnapshotController.cs:line 212\\n--- End of stack trace from previous location where exception was thrown ---\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()\\n--- End of stack trace from previous location where exception was thrown ---\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()\\n--- End of stack trace from previous location where exception was thrown ---\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()\\n--- End of stack trace from previous location where exception was thrown ---\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()\",\n      \"innerException\": null,\n      \"data\": {},\n      \"errorResponse\": null\n    }\n  },\n  \"correlation\": {\n    \"operation\": \"e8794bd4-4dafe5d5581f0658\",\n    \"request\": \"oA3MIPtyhU4=\"\n  }\n}"
}
Accept header absent and forced to application/json
Accept header absent and forced to application/json
Client-Request-ID=49bfb5bb-7095-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Fri, 15 Jun 2018 12:11:53 GMT, Server-Request-ID=b49fa0d5-f01e-006c-76a2-04f0b7000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:b49fa0d5-f01e-006c-76a2-04f0b7000000Time:2018-06-15T12:11:53.5883507Z</Message></Error>.
Client-Request-ID=49bfb5bd-7095-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Fri, 15 Jun 2018 12:11:53 GMT, Server-Request-ID=cc1356c4-e01e-0096-4aa2-043950000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:cc1356c4-e01e-0096-4aa2-043950000000Time:2018-06-15T12:11:53.7769671Z</Message></Error>.
Client-Request-ID=49bfb5bf-7095-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Fri, 15 Jun 2018 12:11:53 GMT, Server-Request-ID=7fb38776-201e-0047-1ca2-04840f000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:7fb38776-201e-0047-1ca2-04840f000000Time:2018-06-15T12:11:53.9467557Z</Message></Error>.
Client-Request-ID=49bfb5c1-7095-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Fri, 15 Jun 2018 12:11:53 GMT, Server-Request-ID=13bf14bf-801e-0086-4da2-040fb6000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:13bf14bf-801e-0086-4da2-040fb6000000Time:2018-06-15T12:11:54.1087671Z</Message></Error>.
Already on 'master'
