Switched to branch 'candidate'
Client-Request-ID=a440ec09-6a31-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Thu, 07 Jun 2018 09:03:28 GMT, Server-Request-ID=407dd968-401e-00b1-3f3e-feac4c000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:407dd968-401e-00b1-3f3e-feac4c000000Time:2018-06-07T09:03:28.2578069Z</Message></Error>.
Client-Request-ID=a440ec0b-6a31-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Thu, 07 Jun 2018 09:03:28 GMT, Server-Request-ID=672a1f13-a01e-005e-663e-fea732000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:672a1f13-a01e-005e-663e-fea732000000Time:2018-06-07T09:03:28.4255510Z</Message></Error>.
Client-Request-ID=a440ec0d-6a31-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Thu, 07 Jun 2018 09:03:27 GMT, Server-Request-ID=8702e243-d01e-00bf-563e-fe4047000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:8702e243-d01e-00bf-563e-fe4047000000Time:2018-06-07T09:03:28.5840611Z</Message></Error>.
Client-Request-ID=a440ec0f-6a31-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Thu, 07 Jun 2018 09:03:28 GMT, Server-Request-ID=7335ed4b-e01e-00bc-523e-fe4340000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:7335ed4b-e01e-00bc-523e-fe4340000000Time:2018-06-07T09:03:28.7455838Z</Message></Error>.
Traceback (most recent call last):
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azureml/core/webservice/webservice.py", line 291, in _deploy_webservice
    resp.raise_for_status()
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://eastus2.modelmanagement.azureml.net/api/subscriptions/fac34303-435d-4486-8c3f-7094d82a0b60/resourceGroups/aml-notebooks/providers/Microsoft.MachineLearningServices/workspaces/haieastus2ws3/services?api-version=2018-03-01-preview

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./01.interactive.e2e.py", line 139, in <module>
    driver = 'score.py')
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azureml/core/workspace.py", line 787, in deploy_webservice
    return Webservice.deploy_from_image(self, name, image, deploy_config, target)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azureml/core/webservice/webservice.py", line 253, in deploy_from_image
    return child._deploy(workspace, name, image, deployment_config)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azureml/core/webservice/aci.py", line 108, in _deploy
    return Webservice._deploy_webservice(workspace, name, create_payload, AciWebservice)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azureml/core/webservice/webservice.py", line 296, in _deploy_webservice
    'Content: {}'.format(resp.status_code, resp.headers, resp.content))
azureml.exceptions.azureml_exception.WebserviceException: Received bad response from Model Management Service:
Response Code: 409
Headers: {'Date': 'Thu, 07 Jun 2018 09:05:04 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'api-supported-versions': '2018-03-01-preview', 'x-ms-client-request-id': '5a1fbca4e1ec4795a4c925cd481b5ca1', 'x-ms-client-session-id': '', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains; preload'}
Content: b'{"code":"Conflict","statusCode":409,"message":"Conflict","details":[{"code":"ServiceWithNameExists","message":"Workspace haieastus2ws3 already contains a Service with name: rrs01a"}]}'
Client-Request-ID=0ddb3a66-6a36-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Thu, 07 Jun 2018 09:35:02 GMT, Server-Request-ID=9777ff87-c01e-0089-5342-feed15000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:9777ff87-c01e-0089-5342-feed15000000Time:2018-06-07T09:35:02.9188670Z</Message></Error>.
Client-Request-ID=0ddb3a68-6a36-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Thu, 07 Jun 2018 09:35:02 GMT, Server-Request-ID=a9018646-201e-0022-1242-fe3a07000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:a9018646-201e-0022-1242-fe3a07000000Time:2018-06-07T09:35:03.2463509Z</Message></Error>.
Client-Request-ID=0ddb3a6a-6a36-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Thu, 07 Jun 2018 09:35:03 GMT, Server-Request-ID=a48c620a-f01e-006f-3e42-fefce5000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:a48c620a-f01e-006f-3e42-fefce5000000Time:2018-06-07T09:35:03.4143034Z</Message></Error>.
Client-Request-ID=0ddb3a6c-6a36-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Thu, 07 Jun 2018 09:35:02 GMT, Server-Request-ID=03d29edf-901e-0030-5a42-fe0e1b000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:03d29edf-901e-0030-5a42-fe0e1b000000Time:2018-06-07T09:35:03.5738513Z</Message></Error>.
Traceback (most recent call last):
  File "./10.o16n.py", line 88, in <module>
    model.delete()
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azureml/core/model.py", line 313, in delete
    'Content: {}'.format(resp.status_code, resp.headers, resp.content))
azureml.exceptions.azureml_exception.WebserviceException: Received bad response from Model Management Service:
Response Code: 412
Headers: {'Date': 'Thu, 07 Jun 2018 09:42:27 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'api-supported-versions': '2018-03-01-preview', 'x-ms-client-request-id': '10f5e30b87ac4726bb94442313b28e84', 'x-ms-client-session-id': '', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains; preload'}
Content: b'{"code":"PreconditionFailed","statusCode":412,"message":"PreconditionFailed","details":[{"code":"DeletionRequired","message":"The model with id mymodel:26 can not be deleted because it is currently being used in one or more images"}]}'
error: Your local changes to the following files would be overwritten by checkout:
	e2e_test/best_model.pkl
	e2e_test/mse_over_alpha.png
Please, commit your changes or stash them before you can switch branches.
Aborting
