Switched to branch 'candidate'
WARNING:cli.azure.cli.core._profile:To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code FXAQZJGES to authenticate.
Traceback (most recent call last):
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azure/cli/command_modules/profile/custom.py", line 134, in login
    allow_no_subscriptions=allow_no_subscriptions)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 183, in find_subscriptions_on_login
    tenant, self._ad_resource_uri)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 740, in find_through_interactive_flow
    token_entry = context.acquire_token_with_device_code(resource, code, _CLIENT_ID)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/adal/authentication_context.py", line 296, in acquire_token_with_device_code
    return self._acquire_token(token_func, user_code_info.get('correlation_id', None))
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/adal/authentication_context.py", line 128, in _acquire_token
    return token_func(self)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/adal/authentication_context.py", line 289, in token_func
    token = token_request.get_token_with_device_code(user_code_info)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/adal/token_request.py", line 397, in get_token_with_device_code
    token = client.get_token_with_polling(oauth_parameters, interval, expires_in)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/adal/oauth2_client.py", line 362, in get_token_with_polling
    wire_response)
adal.adal_error.AdalError: Unexpected polling state code_expired

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./01.interactive.e2e.py", line 30, in <module>
    ws = Workspace.from_config()
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azureml/core/workspace.py", line 135, in from_config
    resource_group=resource_group_from_config, auth=auth)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azureml/core/workspace.py", line 259, in get_or_create
    resource_group=resource_group)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azureml/core/workspace.py", line 202, in get
    auth = InteractiveLoginAuthentication()
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azureml/core/authentication.py", line 189, in __init__
    az_cli_custom.login(DummyCommandLoader())
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azure/cli/command_modules/profile/custom.py", line 144, in login
    raise CLIError(err)
knack.util.CLIError: Unexpected polling state code_expired
WARNING:cli.azure.cli.core._profile:To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code FLLTRBE49 to authenticate.
Traceback (most recent call last):
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azure/cli/command_modules/profile/custom.py", line 134, in login
    allow_no_subscriptions=allow_no_subscriptions)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 183, in find_subscriptions_on_login
    tenant, self._ad_resource_uri)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 740, in find_through_interactive_flow
    token_entry = context.acquire_token_with_device_code(resource, code, _CLIENT_ID)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/adal/authentication_context.py", line 296, in acquire_token_with_device_code
    return self._acquire_token(token_func, user_code_info.get('correlation_id', None))
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/adal/authentication_context.py", line 128, in _acquire_token
    return token_func(self)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/adal/authentication_context.py", line 289, in token_func
    token = token_request.get_token_with_device_code(user_code_info)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/adal/token_request.py", line 397, in get_token_with_device_code
    token = client.get_token_with_polling(oauth_parameters, interval, expires_in)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/adal/oauth2_client.py", line 362, in get_token_with_polling
    wire_response)
adal.adal_error.AdalError: Unexpected polling state code_expired

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./02.local.py", line 19, in <module>
    ws = Workspace.from_config()
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azureml/core/workspace.py", line 135, in from_config
    resource_group=resource_group_from_config, auth=auth)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azureml/core/workspace.py", line 259, in get_or_create
    resource_group=resource_group)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azureml/core/workspace.py", line 202, in get
    auth = InteractiveLoginAuthentication()
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azureml/core/authentication.py", line 189, in __init__
    az_cli_custom.login(DummyCommandLoader())
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azure/cli/command_modules/profile/custom.py", line 144, in login
    raise CLIError(err)
knack.util.CLIError: Unexpected polling state code_expired
WARNING:cli.azure.cli.core._profile:To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code FJQJXASL5 to authenticate.
Traceback (most recent call last):
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azure/cli/command_modules/profile/custom.py", line 134, in login
    allow_no_subscriptions=allow_no_subscriptions)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 183, in find_subscriptions_on_login
    tenant, self._ad_resource_uri)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 740, in find_through_interactive_flow
    token_entry = context.acquire_token_with_device_code(resource, code, _CLIENT_ID)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/adal/authentication_context.py", line 296, in acquire_token_with_device_code
    return self._acquire_token(token_func, user_code_info.get('correlation_id', None))
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/adal/authentication_context.py", line 128, in _acquire_token
    return token_func(self)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/adal/authentication_context.py", line 289, in token_func
    token = token_request.get_token_with_device_code(user_code_info)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/adal/token_request.py", line 397, in get_token_with_device_code
    token = client.get_token_with_polling(oauth_parameters, interval, expires_in)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/adal/oauth2_client.py", line 362, in get_token_with_polling
    wire_response)
adal.adal_error.AdalError: Unexpected polling state code_expired

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./03.aci.py", line 20, in <module>
    ws = Workspace.from_config()
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azureml/core/workspace.py", line 135, in from_config
    resource_group=resource_group_from_config, auth=auth)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azureml/core/workspace.py", line 259, in get_or_create
    resource_group=resource_group)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azureml/core/workspace.py", line 202, in get
    auth = InteractiveLoginAuthentication()
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azureml/core/authentication.py", line 189, in __init__
    az_cli_custom.login(DummyCommandLoader())
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azure/cli/command_modules/profile/custom.py", line 144, in login
    raise CLIError(err)
knack.util.CLIError: Unexpected polling state code_expired
WARNING:cli.azure.cli.core._profile:To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code FJL8Y3RGY to authenticate.
Traceback (most recent call last):
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azure/cli/command_modules/profile/custom.py", line 134, in login
    allow_no_subscriptions=allow_no_subscriptions)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 183, in find_subscriptions_on_login
    tenant, self._ad_resource_uri)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 740, in find_through_interactive_flow
    token_entry = context.acquire_token_with_device_code(resource, code, _CLIENT_ID)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/adal/authentication_context.py", line 296, in acquire_token_with_device_code
    return self._acquire_token(token_func, user_code_info.get('correlation_id', None))
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/adal/authentication_context.py", line 128, in _acquire_token
    return token_func(self)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/adal/authentication_context.py", line 289, in token_func
    token = token_request.get_token_with_device_code(user_code_info)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/adal/token_request.py", line 397, in get_token_with_device_code
    token = client.get_token_with_polling(oauth_parameters, interval, expires_in)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/adal/oauth2_client.py", line 362, in get_token_with_polling
    wire_response)
adal.adal_error.AdalError: Unexpected polling state code_expired

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./04.dsvm.py", line 19, in <module>
    ws = Workspace.from_config()
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azureml/core/workspace.py", line 135, in from_config
    resource_group=resource_group_from_config, auth=auth)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azureml/core/workspace.py", line 259, in get_or_create
    resource_group=resource_group)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azureml/core/workspace.py", line 202, in get
    auth = InteractiveLoginAuthentication()
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azureml/core/authentication.py", line 189, in __init__
    az_cli_custom.login(DummyCommandLoader())
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azure/cli/command_modules/profile/custom.py", line 144, in login
    raise CLIError(err)
knack.util.CLIError: Unexpected polling state code_expired
WARNING:cli.azure.cli.core._profile:To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code FF4Z4F6UW to authenticate.
Traceback (most recent call last):
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azure/cli/command_modules/profile/custom.py", line 134, in login
    allow_no_subscriptions=allow_no_subscriptions)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 183, in find_subscriptions_on_login
    tenant, self._ad_resource_uri)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 740, in find_through_interactive_flow
    token_entry = context.acquire_token_with_device_code(resource, code, _CLIENT_ID)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/adal/authentication_context.py", line 296, in acquire_token_with_device_code
    return self._acquire_token(token_func, user_code_info.get('correlation_id', None))
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/adal/authentication_context.py", line 128, in _acquire_token
    return token_func(self)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/adal/authentication_context.py", line 289, in token_func
    token = token_request.get_token_with_device_code(user_code_info)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/adal/token_request.py", line 397, in get_token_with_device_code
    token = client.get_token_with_polling(oauth_parameters, interval, expires_in)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/adal/oauth2_client.py", line 362, in get_token_with_polling
    wire_response)
adal.adal_error.AdalError: Unexpected polling state code_expired

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./05.spark.py", line 19, in <module>
    ws = Workspace.from_config()
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azureml/core/workspace.py", line 135, in from_config
    resource_group=resource_group_from_config, auth=auth)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azureml/core/workspace.py", line 259, in get_or_create
    resource_group=resource_group)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azureml/core/workspace.py", line 202, in get
    auth = InteractiveLoginAuthentication()
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azureml/core/authentication.py", line 189, in __init__
    az_cli_custom.login(DummyCommandLoader())
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azure/cli/command_modules/profile/custom.py", line 144, in login
    raise CLIError(err)
knack.util.CLIError: Unexpected polling state code_expired
WARNING:cli.azure.cli.core._profile:To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code FFH4NMC72 to authenticate.
Traceback (most recent call last):
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/urllib3/connection.py", line 171, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/urllib3/util/connection.py", line 56, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/urllib3/connectionpool.py", line 849, in _validate_conn
    conn.connect()
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/urllib3/connection.py", line 314, in connect
    conn = self._new_conn()
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/urllib3/connection.py", line 180, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f98f91579e8>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /common/oauth2/token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f98f91579e8>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azure/cli/command_modules/profile/custom.py", line 134, in login
    allow_no_subscriptions=allow_no_subscriptions)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 183, in find_subscriptions_on_login
    tenant, self._ad_resource_uri)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 740, in find_through_interactive_flow
    token_entry = context.acquire_token_with_device_code(resource, code, _CLIENT_ID)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/adal/authentication_context.py", line 296, in acquire_token_with_device_code
    return self._acquire_token(token_func, user_code_info.get('correlation_id', None))
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/adal/authentication_context.py", line 128, in _acquire_token
    return token_func(self)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/adal/authentication_context.py", line 289, in token_func
    token = token_request.get_token_with_device_code(user_code_info)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/adal/token_request.py", line 397, in get_token_with_device_code
    token = client.get_token_with_polling(oauth_parameters, interval, expires_in)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/adal/oauth2_client.py", line 345, in get_token_with_polling
    verify=self._call_context.get('verify_ssl', None))
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/requests/adapters.py", line 513, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /common/oauth2/token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f98f91579e8>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./07.sklearn.hd.py", line 21, in <module>
    ws = Workspace.from_config()
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azureml/core/workspace.py", line 135, in from_config
    resource_group=resource_group_from_config, auth=auth)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azureml/core/workspace.py", line 259, in get_or_create
    resource_group=resource_group)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azureml/core/workspace.py", line 202, in get
    auth = InteractiveLoginAuthentication()
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azureml/core/authentication.py", line 189, in __init__
    az_cli_custom.login(DummyCommandLoader())
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azure/cli/command_modules/profile/custom.py", line 146, in login
    raise CLIError('Please ensure you have network connection. Error detail: ' + str(err))
knack.util.CLIError: Please ensure you have network connection. Error detail: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /common/oauth2/token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f98f91579e8>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
WARNING:cli.azure.cli.core._profile:To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code FNW7JA73X to authenticate.
Traceback (most recent call last):
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azure/cli/command_modules/profile/custom.py", line 134, in login
    allow_no_subscriptions=allow_no_subscriptions)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 183, in find_subscriptions_on_login
    tenant, self._ad_resource_uri)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 740, in find_through_interactive_flow
    token_entry = context.acquire_token_with_device_code(resource, code, _CLIENT_ID)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/adal/authentication_context.py", line 296, in acquire_token_with_device_code
    return self._acquire_token(token_func, user_code_info.get('correlation_id', None))
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/adal/authentication_context.py", line 128, in _acquire_token
    return token_func(self)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/adal/authentication_context.py", line 289, in token_func
    token = token_request.get_token_with_device_code(user_code_info)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/adal/token_request.py", line 397, in get_token_with_device_code
    token = client.get_token_with_polling(oauth_parameters, interval, expires_in)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/adal/oauth2_client.py", line 362, in get_token_with_polling
    wire_response)
adal.adal_error.AdalError: Unexpected polling state code_expired

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./08.tf.hd.py", line 22, in <module>
    ws = Workspace.from_config()
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azureml/core/workspace.py", line 135, in from_config
    resource_group=resource_group_from_config, auth=auth)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azureml/core/workspace.py", line 259, in get_or_create
    resource_group=resource_group)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azureml/core/workspace.py", line 202, in get
    auth = InteractiveLoginAuthentication()
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azureml/core/authentication.py", line 189, in __init__
    az_cli_custom.login(DummyCommandLoader())
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azure/cli/command_modules/profile/custom.py", line 144, in login
    raise CLIError(err)
knack.util.CLIError: Unexpected polling state code_expired
WARNING:cli.azure.cli.core._profile:To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code FC6CW9KVF to authenticate.
Traceback (most recent call last):
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azure/cli/command_modules/profile/custom.py", line 134, in login
    allow_no_subscriptions=allow_no_subscriptions)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 183, in find_subscriptions_on_login
    tenant, self._ad_resource_uri)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 740, in find_through_interactive_flow
    token_entry = context.acquire_token_with_device_code(resource, code, _CLIENT_ID)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/adal/authentication_context.py", line 296, in acquire_token_with_device_code
    return self._acquire_token(token_func, user_code_info.get('correlation_id', None))
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/adal/authentication_context.py", line 128, in _acquire_token
    return token_func(self)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/adal/authentication_context.py", line 289, in token_func
    token = token_request.get_token_with_device_code(user_code_info)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/adal/token_request.py", line 397, in get_token_with_device_code
    token = client.get_token_with_polling(oauth_parameters, interval, expires_in)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/adal/oauth2_client.py", line 362, in get_token_with_polling
    wire_response)
adal.adal_error.AdalError: Unexpected polling state code_expired

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./10.o16n.py", line 25, in <module>
    ws = Workspace.from_config('./aml_config/config.json')
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azureml/core/workspace.py", line 135, in from_config
    resource_group=resource_group_from_config, auth=auth)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azureml/core/workspace.py", line 259, in get_or_create
    resource_group=resource_group)
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azureml/core/workspace.py", line 202, in get
    auth = InteractiveLoginAuthentication()
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azureml/core/authentication.py", line 189, in __init__
    az_cli_custom.login(DummyCommandLoader())
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azure/cli/command_modules/profile/custom.py", line 144, in login
    raise CLIError(err)
knack.util.CLIError: Unexpected polling state code_expired
Already on 'master'
